const internships = [["[", false],
                     ["  { 'company': 'E3 Technology Inc.',", false],
                     ["    'title': 'Associate Security Consultant',", false],
                     ["    'period': 'May 2021 - November 2021',", false],
                     ["    'duties': [", false],
                     ["'* Internal and external penetration testing and vulnerability assessment',", false],
                     ["'* Social engineering over the phone for phishing campaigns',", false],
                     ["'* Automating repetitive audit tasks with scripts and containerizing with Docker',", false],
                     ["'* Reporting findings to technical audiences clearly and concisely']", false],
                     ["  },", false],
                     ["  { 'company': 'METER Group',", false],
                     ["    'title': 'Research Intern',", false],
                     ["    'period': 'May 2020 - August 2020',", false],
                     ["    'duties': [", false],
                     ["'* Explored the use of Time Domain Reflectometry (TDR) as an application in ground meats',", false],
                     ["'* Designed experiments to control for external factors against target measurements']", false],
                     ["  },", false],
                     ["  { 'company: 'METER Group',", false],
                     ["    'title': 'Firmware Engineering Intern',", false],
                     ["    'period': 'May 2019 - August 2019',"],
                     ["    'duties': [", false],
                     ["'* QA testing to find bugs in code written by other developers',", false],
                     ["'* Designing experiments to determine product battery life in the field']", false],
                     ["  }", false],
                     ["]", false]]

export default internships;